# -*- coding: utf-8 -*-
"""task1c.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eri8wRHp-d9R20WgpGGZSeVjHITDv1gp
"""

from pandas import *
 
# reading CSV file
jagdish_data= read_csv("Trails.csv")

Find_Status= jagdish_data['STATUS'].tolist() # to find the status
my_count=0
for item in Find_Status: # for lop used 
  if item=='ACTIVE':
    my_count=my_count+1
print(my_count) 

find_light= jagdish_data['LIGHT'].tolist() # from my list
count_my_light=0
for item in find_light:
  if item=='Yes':
    count_my_light=count_my_light+1
print(count_my_light)