# -*- coding: utf-8 -*-
"""task1b.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_lqPDYn38Mcc5oVWZGCWnfP83sXfnLv
"""

from pandas import *
 
# reading CSV file
g_data = read_csv("Trails.csv")

# converting column data to list

Inst_year = g_data['INST_YEAR'].tolist()
count=0
for item in Inst_year: # used for loop here
  if item>2000: # condition used here
    count=count+1 # increment by 1
print(count)