# -*- coding: utf-8 -*-
"""task11.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6gxzBqhRdUseHcZr_MiqVY-IuYpCGy5
"""

import pandas as pd

data = pd.read_csv("Trails.csv")

import csv
good=[]
poor=[]
marginal=[]

unknown=[]
# Open file
with open('Trails.csv') as file_obj:

    reader_obj = csv.reader(file_obj)
    for row in reader_obj:
        if row[9]=='GOOD':
            good.append(row)
        elif row[9]=='POOR':
            poor.append(row)
        elif row[9]=='MARGINAL':
            marginal.append(row)
        elif row[9]=='':
            unknown.append(row)
        elif row[9]=='Unknown':
            unknown.append(row)
        else:
            print("got other value")
            print(row[9])

print("List of good")
print(*good,sep='\n')
print("list of poor")
print(*poor,sep='\n')


print("List of marginal")
print(*marginal,sep='\n')
print("List of unknown")
print(*unknown,sep='\n')