# -*- coding: utf-8 -*-
"""task1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6gxzBqhRdUseHcZr_MiqVY-IuYpCGy5
"""

import pandas as pd

data = pd.read_csv("Trails.csv")