# -*- coding: utf-8 -*-
"""task3c.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZR9nSI9KxB__3humv0oQi0-IZBvUDT4E
"""

def sorted_words(): # function created
  book1 = open(book1,'r')
  lines = book1.readlines()
  output=[len(i) for i in lines]
  return output.sort() # return statement used