# -*- coding: utf-8 -*-
"""task1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BZ46AiCynX1fTO8QoxQGvP_PCSoPFm8i
"""

from pandas import * # used import statemnet
 
#  To read CSV file
data = read_csv("Trails.csv")
 
# converting column data to list
TRAIL_ID = data['TRAIL_ID'].tolist() # to get data with trail id
TRAIL_NAME = data['TRAIL_NAME'].tolist()
general_condition = data['CONDITION'].tolist() # based on condition
print('TRAIL_ID:', TRAIL_ID)
print('TRAIL_NAME',TRAIL_NAME)
print('general_condition:', general_condition)