# -*- coding: utf-8 -*-
"""task0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aS3ePfkYbOhCAVB71SF--WD1C-V4r5WS
"""

for fizzbuzz in range(1,100):
    if fizzbuzz % 15 == 0:
        print("FizzBuzz") 
        continue
    elif fizzbuzz % 3 == 0:
        print("Fizz") 
        continue
    elif fizzbuzz % 5 == 0:
        print("Buzz")
        continue 
    print(fizzbuzz)